# theme
import = ["~/.config/alacritty/themes/dracula/theme.toml"]

[window]

padding = {x=3,y=2}
opacity = 0.8


[font]

normal = {family = "Hack Nerd Font", style = "Regular"}
size = 8
offset = { x = 1, y = 0 }

[shell]

program = "/usr/bin/tmux"
args = ["new-session"]
